export const VIEWPORTS = [
  'teachfloor.dashboard.course.list',
  'teachfloor.dashboard.course.detail',
  'teachfloor.dashboard.course.module.detail',
  'teachfloor.dashboard.course.element.detail',
  'teachfloor.dashboard.community.post.list',
  'teachfloor.dashboard.community.member.list',
  'teachfloor.dashboard.settings.general.detail',
  'teachfloor.dashboard.settings.customization.detail',
  'teachfloor.dashboard.settings.team.list',
  'teachfloor.dashboard.settings.billing.detail',
  'teachfloor.dashboard.settings.integration.list',
  'teachfloor.dashboard.settings.notification.list',
  'teachfloor.dashboard.settings.custom-field.list',
  'teachfloor.dashboard.account.detail',
  'teachfloor.dashboard.learner.list',
  'teachfloor.dashboard.payment.list',
];